### ISSUE TITLE
No VA display found for device error until container restarted

### ISSUE THREAD

**Issue by mtrolley** [mdhiggins/sonarr-sma#63] opened 2024-10-29 22:47 UTC
I doubt this is a problem with this container, but recently I've been getting this error:

```
[AVHWDeviceContext @ 0x7ff3182f4e00] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value 'vaapi=sma:/dev/dri/renderD128' for option 'init_hw_device': Invalid argument
Error parsing global options: Invalid argument

2024-10-29 13:58:01 - SonarrPostProcess - ERROR - Processing returned False.
2024-10-29 13:58:01 - SonarrPostProcess - ERROR - Error processing file.
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 230, in <module>
    sys.exit(1)
SystemExit: 1
```

Let me know if more context is needed.

This happens when sonarr post-processing runs. What I've found is that simply restarting the container fixes the problem, in that I can run a shell in the container and run a manual conversion no problem. I didn't have this before, so I'm not sure what changed. I'm hoping someone else that uses this container may know.

**Comment by mdhiggins** [comment] 2024-10-30 06:15
Nothing has changed in a while. This is an ffmpeg error from it not having access to your hardware device. Are the manual conversions your triggering actually using hardware encoding? Probably need to share your docker info too to make sure the hardware is actually passed correctly.

**Comment by mtrolley** [comment] 2024-10-30 10:48
I realize I wasn't completely right when I said "nothing has changed" because what I _did_ change was switching from one monolithic `docker-compose.yaml` file into separate files for each container and having the main compose file `include` the others. The contents didn't change other than reformatting from what I remember though. Here's the docker compose for sonarr:

```
services:
  sonarr:
    container_name: sonarr
    devices:
      - /dev/dri:/dev/dri
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      SMA_HWACCEL: "true"
      SMA_USE_REPO: "true"
      TZ: "${TZ}"
    hostname: sonarr
    image: mdhiggins/sonarr-sma
    labels:
      - swag=enable
    ports:
      - 8989:8989
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${VOLUME_CONFIG}/sonarr
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: ${VOLUME_CONFIG}/sonarr-sma
        target: /usr/local/sma/config
      - type: bind
        source: ${VOLUME_STORAGE}
        target: /storage
```

[Here's two logs](https://gist.github.com/mtrolley/daae832c4d45de7560aaf6187b4f000b). `failed.txt` is the log from the last file that failed when triggered by Sonarr postprocessing. `manual.txt` is the same file being processed manually and successfully after restarting the container. It's definitely uses hardware because I can check with `intel_gpu_top` and see it being used.

**Comment by mtrolley** [comment] 2024-10-30 10:53
I notice a difference from your instructions; you have:

```
devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
```

I have:

```
devices:
  - /dev/dri:/dev/dri
```

I'm sure I didn't change that from before, but what I have is less specific so I'll update it.

**Comment by mdhiggins** [comment] 2024-10-30 21:02
I wonder if maybe this is a permissions issue. When you log in manually and trigger stuff it's probably running as container root. When things run normally it's using your PUID/PGID (as abc:abc). If your /dev/dri device doesn't isn't given the appropriate permission on your system so the PUID/PGID can use it, it might fail with that error message but pass manually

**Comment by mtrolley** [comment] 2024-10-30 21:27
Interesting, I should know by tomorrow. There's a show scheduled to download later tonight so I will check the log and update this thread.

**Comment by mdhiggins** [comment] 2024-10-30 22:03
For reference here's what I have on my setup

```
drwxr-xr-x 2 root root         80 Sep 20 23:21 by-path
crw-rw---- 1 root video  226,   0 Sep 20 23:21 card0
crw-rw---- 1 root render 226, 128 Sep 20 23:21 renderD128
```

And my dockeruser (which is what my PUID points to) groups are

```
dockeruser : dockeruser tty uucp dialout video render docker
```
With `video` and `render` being the important groups (this is all on the main system, outside of the container)

**Comment by mtrolley** [comment] 2024-10-30 23:05
Looks similar, but my user isn't in `video`:

```
❯ ll /dev/dri
total 0
drwxr-xr-x 2 root root         80 Oct 22 19:37 by-path
crw-rw---- 1 root video  226,   0 Oct 22 19:37 card0
crw-rw---- 1 root render 226, 128 Oct 22 19:37 renderD128
❯ id
uid=1000(trolley) gid=1000(trolley) groups=1000(trolley),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),109(render),110(lxd),999(docker)
```

I'll add `video`.

**Comment by mtrolley** [comment] 2024-10-30 23:31
I tried this: `docker exec -it --user abc sonarr /bin/bash` and tried manually running a conversion and it's working. I'll see how the postprocessing of an automatic download works tonight.

**Comment by mtrolley** [comment] 2024-10-31 10:36
Everything worked perfectly fine with the last show that downloaded so I'm going to close this and keep an eye on it and comment if it happens again.

**Comment by mtrolley** [comment] 2024-11-04 18:12
It happened again and I discovered a few new things:
- Restarting the container isn't needed to manually process (even as user abc) but the postSonarr script fails with this error until the container is restarted.
- It looks like the problem starts when Watchtower upgrades the container image. Everything was working fine until that happened. I don't know enough about Watchtower to know why that might be so I'll disable it on this container.

**Comment by mdhiggins** [comment] 2024-11-05 01:38
No idea what watchtower is

**Comment by mtrolley** [comment] 2024-11-05 01:39
It's a docker container that automatically updates your other containers when new images get released: https://containrrr.dev/watchtower/

I'm not going to use it anymore anyway. Thanks for your time though, I really appreciate it.

**Comment by mdhiggins** [comment] 2024-11-05 01:40
https://www.reddit.com/r/jellyfin/comments/z1pgdv/transcoding_stopped_working/

Maybe that'll help?

**Comment by mtrolley** [comment] 2024-11-11 03:13
I may have found the problem, but don't understand why it only affects me.

I updated my radarr-sma and sonarr-sma images today manually and had the same problem. I checked the logs and see this the first time both booted after upgrade:

```
2024-11-10T15:28:20.074941988Z [custom-init] No custom files found, skipping...
2024-11-10T15:28:20.190965935Z **** creating video group video0v8j with id 109 ****
2024-11-10T15:28:20.190978339Z **** adding /dev/dri/renderD128 to video group video0v8j with id 109 ****
2024-11-10T15:28:20.289801035Z [90-sma-config] SMA config initialized
M
```

The next `postRadarr.py` failed. I restarted the container, and sure enough it works. I see this in the log on the restart:

```
2024-11-11T02:50:57.615588639Z **** permissions for /dev/dri/renderD128 are good ****
2024-11-11T02:50:57.620511873Z [90-sma-config] SMA config initialized
2024-11-11T02:50:57.660394726Z [custom-init] No custom files found, skipping...
```

Could it be that the creation of the video group and adding user `abc` to it needs the container to restart to take effect?

**Comment by mdhiggins** [comment] 2024-11-11 22:13
Can't reproduce this on my end

Are you seeing any errors when you check and first start the container? There is a script that runs that handles setting the permissions on those devices at the container start that might be throwing some errors

Script is
https://github.com/mdhiggins/sonarr-sma/blob/master/root/etc/s6-overlay/s6-rc.d/init-gid-video/run

I did just push an update that syncs this with the latest version of the script from linuxserver, though it doesn't look like they made any actual functional changes so I can't imagine this would make much difference but can't hurt to update and see

**Comment by mdhiggins** [comment] 2024-11-11 22:13
Out of curiosity, using the stock linuxserver plex container (which includes the hardware support and the same script) do you see the same behavior?

**Comment by mtrolley** [comment] 2024-11-11 22:28
I can’t remember the last time there was an update to that one, but I am
going to test when there is. I know that hardware acceleration is working
fine in my Plex container right now so I need to reproduce installing an
updated container.

**Comment by mtrolley** [comment] 2024-11-11 22:49
I just updated and got a new build of radarr-sma so I did a test, and got the same thing. Here are the logs:

radarr-sma log: https://gist.github.com/mtrolley/3e62f82ee62dc05cdbc704a6d9f7362f
sma log: https://gist.github.com/mtrolley/7461f9bcc5e60748e1c19245778d6858

I don't see anything out of the ordinary in the radarr-sma logs. The only thing I removed was the info about checking indexers for releases, like 7 lines.

I'm going to leave the radarr container like this in case there's anything you want me to check.

**Comment by mdhiggins** [comment] 2024-11-14 23:42
Looks like the lines generated by the device permission script are showing up correctly

```
[custom-init] No custom files found, skipping...
**** creating video group videoh8sf with id 109 ****
**** adding /dev/dri/renderD128 to video group videoh8sf with id 109 ****
```

Did you happen to see if the linuxserver plex container has issues? It uses the same script just wondering if its a universal linuxserver container problem or not

**Comment by mtrolley** [comment] 2024-11-15 02:30
I haven’t seen an update to it yet but will try as soon as I can. I did
compare the script that you have in your repos to the one they have and
there are slight differences, but I don’t think they affect the
functionality.

**Comment by mdhiggins** [comment] 2024-11-15 02:34
I think it should be identical I just updated it when you opened this issue to make sure it was the same but agreed they were just minor changes unlikely to have functional implications

Keep me posted

**Comment by mtrolley** [comment] 2024-11-16 18:07
There was a Plex container update so I updated it and it works totally fine. I tried recreating the radarr-sma container using the Nov. 11 image and get the same error as here:

```
[AVHWDeviceContext @ 0x7fa3577fce00] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value 'vaapi=sma:/dev/dri/renderD128' for option 'init_hw_device': Invalid argument
```

I restarted the container and it's working fine now.

**Comment by mtrolley** [comment] 2024-11-16 18:31
I just did another test. I recreated sonarr-sma container, and verified I got the error above. Then I run a shell in the container and restart Sonarr with:

```
s6-rc -d change svc-sonarr
s6-rc -u change svc-sonarr
```

and it works! Could the `svc-sonarr` service be restarted automatically after the video group script completes?

**Comment by mdhiggins** [comment] 2024-11-16 20:51
Merged and pulled the same change into radarr-sma

Thanks for the solution

**Closed as completed by mdhiggins** 2024-11-16 20:51 UTC
